### ISSUE TITLE
Example has a few missing tags

### ISSUE THREAD

**Issue by Jaxelr** [wotamann/vue-form-base#1]
Greetings,

First of all, this is a very cool library, so thanks for that  :+1:   

I found a couple of issues with the example:

1.  App.vue has 1 missing </form-base> (https://github.com/wotamann/vue-form-base/blob/master/example/vue-form-base/src/App.vue#L112) 
2.  App.vue has a missing </div> from the container (https://github.com/wotamann/vue-form-base/blob/master/example/vue-form-base/src/App.vue#L115)
3. formBase.vue is missing 1 closing tag. </span> (https://github.com/wotamann/vue-form-base/blob/master/example/vue-form-base/src/components/formBase.vue#L89)
4. formBase.vue has an incorrect template tag that should be a tag of radio (https://github.com/wotamann/vue-form-base/blob/master/example/vue-form-base/src/components/formBase.vue#L47)

Im shooting a PR your way to fix all these and get the working sample up and running.

**Comment by wotamann** [comment]
Thanks for your contribution and your wellcome feedback! 

I will accept your PR Pt 1-3). 

Only Pt 4) replacing a<template> tag with <radio> I can't agree. IMHO there exist no <radio> tag in HTML5 and radiobuttons are represented by <input type 'radio' />.

**Comment by Jaxelr** [comment]
Hehehe You're right, i will fix it and submit a patch. :+1: :+1:

**Comment by Jaxelr** [comment]
Done. Thanks!! Added template back to the tags and added the closing template tag that was the original error.
